apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: my-ingress
  namespace: prod
spec:
  rules:
    - http:
        paths:
          - path: /beauty
            pathType: Prefix
            backend:
              service:
                name: beauty-ingress
                port:
                  number: 80
                
    - http:
        paths:
          - path: /highway
            pathType: Prefix
            backend:
              service:
                name: highway-ingress
                port:
                  number: 80
                

